version: '2'
services:
  jenkins-leader:
    build:
      context: ./leader
    image: 085913924494.dkr.ecr.eu-west-1.amazonaws.com/elastera/jenkins-leader:latest
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins-follower-basic:
    build:
      context: ./follower/basic
    image: 085913924494.dkr.ecr.eu-west-1.amazonaws.com/elastera/jenkins-follower:basic
    ports:
      - "22:9022"
  jenkins-follower-chef:
    build:
      context: ./follower/chef
    image: 085913924494.dkr.ecr.eu-west-1.amazonaws.com/elastera/jenkins-follower:chef
    ports:
      - "22:9022"
  jenkins-follower-packer:
    build:
      context: ./follower/packer
    image: 085913924494.dkr.ecr.eu-west-1.amazonaws.com/elastera/jenkins-follower:packer
  jenkins-follower-terraform:
    build:
      context: ./follower/terraform
    image: 085913924494.dkr.ecr.eu-west-1.amazonaws.com/elastera/jenkins-follower:terraform
  
